security:
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: acme
      client-secret: acmesecret
      user-authorization-uri: http://127.0.0.1:9999/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/oauth/token
      client-authentication-scheme: form
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/oauth/token_key


server:
  port: 8080